# Auto-generated from Peet_Paars_Master_v8_1.xlsx
# Contains kcal per 100g (gram) or per 100ml (ml/cl), and standard portions.

FOOD_LIBRARY = {
  "D001": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 0.0,
    "label": "Water",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D002": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 0.0,
    "label": "Spa rood",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D003": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 1.0,
    "label": "Zwarte koffie",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 200.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D004": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 1.0,
    "label": "Thee",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 200.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D005": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 0.0,
    "label": "Cola zero",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 330.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D006": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 0.0,
    "label": "Zero frisdrank algemeen",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 330.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D007": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 46.0,
    "label": "Halfvolle melk",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D008": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 64.0,
    "label": "Volle melk",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D009": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 85.0,
    "label": "Chocolademelk",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 330.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D010": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 40.0,
    "label": "Havermelk",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D011": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 13.0,
    "label": "Amandelmelk ongezoet",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D012": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 33.0,
    "label": "Sojamelk",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D013": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 42.0,
    "label": "Cola normaal",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 330.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D014": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 45.0,
    "label": "Sinas",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D015": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 30.0,
    "label": "Ice tea",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 330.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D016": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 45.0,
    "label": "Energy drink",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 330.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D017": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 25.0,
    "label": "Sportdrank",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 500.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D018": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 40.0,
    "label": "Cappuccino",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 200.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D019": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 50.0,
    "label": "Latte",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 300.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D020": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 70.0,
    "label": "Latte met siroop",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 300.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D021": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 60.0,
    "label": "Flat white",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 300.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D022": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 90.0,
    "label": "Frappuccino",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 300.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D023": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 43.0,
    "label": "Bier pils",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 330.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D024": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 60.0,
    "label": "IPA",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 330.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D025": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 85.0,
    "label": "Wijn rood",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 150.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D026": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 82.0,
    "label": "Wijn wit",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 150.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D027": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 83.0,
    "label": "Rosé",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 150.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D028": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 90.0,
    "label": "Prosecco",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 150.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D029": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 250.0,
    "label": "Whiskey",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 25.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D030": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 230.0,
    "label": "Vodka",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 25.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D031": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 263.0,
    "label": "Gin",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 25.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D032": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 230.0,
    "label": "Rum",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 25.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D033": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 70.0,
    "label": "Gin tonic",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 25.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D034": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 80.0,
    "label": "Bacardi cola",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D035": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 45.0,
    "label": "Vers sinaasappelsap",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D036": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 60.0,
    "label": "Smoothie fruit",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D037": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 90.0,
    "label": "Proteïneshake",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D038": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 70.0,
    "label": "Chai latte",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 300.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D039": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 60.0,
    "label": "Matcha latte",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 300.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "D040": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 80.0,
    "label": "Koffie met room",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 200.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F001": {
    "kcal_per_100g": 52.0,
    "kcal_per_100ml": None,
    "label": "Appel",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F002": {
    "kcal_per_100g": 57.0,
    "kcal_per_100ml": None,
    "label": "Peer",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F003": {
    "kcal_per_100g": 89.0,
    "kcal_per_100ml": None,
    "label": "Banaan",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F004": {
    "kcal_per_100g": 47.0,
    "kcal_per_100ml": None,
    "label": "Sinaasappel",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F005": {
    "kcal_per_100g": 53.0,
    "kcal_per_100ml": None,
    "label": "Mandarijn",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F006": {
    "kcal_per_100g": 29.0,
    "kcal_per_100ml": None,
    "label": "Citroen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F007": {
    "kcal_per_100g": 30.0,
    "kcal_per_100ml": None,
    "label": "Limoen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F008": {
    "kcal_per_100g": 32.0,
    "kcal_per_100ml": None,
    "label": "Aardbeien",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F009": {
    "kcal_per_100g": 57.0,
    "kcal_per_100ml": None,
    "label": "Bosbessen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F010": {
    "kcal_per_100g": 52.0,
    "kcal_per_100ml": None,
    "label": "Frambozen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F011": {
    "kcal_per_100g": 43.0,
    "kcal_per_100ml": None,
    "label": "Bramen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F012": {
    "kcal_per_100g": 69.0,
    "kcal_per_100ml": None,
    "label": "Druiven",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F013": {
    "kcal_per_100g": 61.0,
    "kcal_per_100ml": None,
    "label": "Kiwi",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F014": {
    "kcal_per_100g": 60.0,
    "kcal_per_100ml": None,
    "label": "Mango",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F015": {
    "kcal_per_100g": 50.0,
    "kcal_per_100ml": None,
    "label": "Ananas",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F016": {
    "kcal_per_100g": 43.0,
    "kcal_per_100ml": None,
    "label": "Papaja",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F017": {
    "kcal_per_100g": 30.0,
    "kcal_per_100ml": None,
    "label": "Watermeloen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F018": {
    "kcal_per_100g": 34.0,
    "kcal_per_100ml": None,
    "label": "Cantaloupe meloen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F019": {
    "kcal_per_100g": 36.0,
    "kcal_per_100ml": None,
    "label": "Honingmeloen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F020": {
    "kcal_per_100g": 83.0,
    "kcal_per_100ml": None,
    "label": "Granaatappel",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F021": {
    "kcal_per_100g": 63.0,
    "kcal_per_100ml": None,
    "label": "Kers",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F022": {
    "kcal_per_100g": 39.0,
    "kcal_per_100ml": None,
    "label": "Perzik",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F023": {
    "kcal_per_100g": 44.0,
    "kcal_per_100ml": None,
    "label": "Nectarine",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F024": {
    "kcal_per_100g": 46.0,
    "kcal_per_100ml": None,
    "label": "Pruim",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F025": {
    "kcal_per_100g": 48.0,
    "kcal_per_100ml": None,
    "label": "Abrikoos",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F026": {
    "kcal_per_100g": 74.0,
    "kcal_per_100ml": None,
    "label": "Vijg vers",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F027": {
    "kcal_per_100g": 97.0,
    "kcal_per_100ml": None,
    "label": "Passievrucht",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F028": {
    "kcal_per_100g": 66.0,
    "kcal_per_100ml": None,
    "label": "Lychee",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F029": {
    "kcal_per_100g": 46.0,
    "kcal_per_100ml": None,
    "label": "Cranberries vers",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "F030": {
    "kcal_per_100g": 63.0,
    "kcal_per_100ml": None,
    "label": "Zwarte bes",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G001": {
    "kcal_per_100g": 34.0,
    "kcal_per_100ml": None,
    "label": "Broccoli",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G002": {
    "kcal_per_100g": 25.0,
    "kcal_per_100ml": None,
    "label": "Bloemkool",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G003": {
    "kcal_per_100g": 41.0,
    "kcal_per_100ml": None,
    "label": "Wortel",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G004": {
    "kcal_per_100g": 23.0,
    "kcal_per_100ml": None,
    "label": "Spinazie",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G005": {
    "kcal_per_100g": 49.0,
    "kcal_per_100ml": None,
    "label": "Boerenkool",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G006": {
    "kcal_per_100g": 31.0,
    "kcal_per_100ml": None,
    "label": "Snijbonen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G007": {
    "kcal_per_100g": 31.0,
    "kcal_per_100ml": None,
    "label": "Sperziebonen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G008": {
    "kcal_per_100g": 31.0,
    "kcal_per_100ml": None,
    "label": "Paprika rood",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G009": {
    "kcal_per_100g": 27.0,
    "kcal_per_100ml": None,
    "label": "Paprika geel",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G010": {
    "kcal_per_100g": 20.0,
    "kcal_per_100ml": None,
    "label": "Paprika groen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G011": {
    "kcal_per_100g": 17.0,
    "kcal_per_100ml": None,
    "label": "Courgette",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G012": {
    "kcal_per_100g": 25.0,
    "kcal_per_100ml": None,
    "label": "Aubergine",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G013": {
    "kcal_per_100g": 18.0,
    "kcal_per_100ml": None,
    "label": "Tomaat",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G014": {
    "kcal_per_100g": 16.0,
    "kcal_per_100ml": None,
    "label": "Komkommer",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G015": {
    "kcal_per_100g": 14.0,
    "kcal_per_100ml": None,
    "label": "IJsbergsla",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G016": {
    "kcal_per_100g": 25.0,
    "kcal_per_100ml": None,
    "label": "Rucola",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G017": {
    "kcal_per_100g": 17.0,
    "kcal_per_100ml": None,
    "label": "Andijvie",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G018": {
    "kcal_per_100g": 17.0,
    "kcal_per_100ml": None,
    "label": "Witlof",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G019": {
    "kcal_per_100g": 31.0,
    "kcal_per_100ml": None,
    "label": "Rode kool",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G020": {
    "kcal_per_100g": 25.0,
    "kcal_per_100ml": None,
    "label": "Witte kool",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G021": {
    "kcal_per_100g": 27.0,
    "kcal_per_100ml": None,
    "label": "Spitskool",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G022": {
    "kcal_per_100g": 31.0,
    "kcal_per_100ml": None,
    "label": "Prei",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G023": {
    "kcal_per_100g": 40.0,
    "kcal_per_100ml": None,
    "label": "Ui",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G024": {
    "kcal_per_100g": 40.0,
    "kcal_per_100ml": None,
    "label": "Rode ui",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G025": {
    "kcal_per_100g": 32.0,
    "kcal_per_100ml": None,
    "label": "Lente-ui",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G026": {
    "kcal_per_100g": 149.0,
    "kcal_per_100ml": None,
    "label": "Knoflook",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G027": {
    "kcal_per_100g": 16.0,
    "kcal_per_100ml": None,
    "label": "Radijs",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G028": {
    "kcal_per_100g": 43.0,
    "kcal_per_100ml": None,
    "label": "Biet gekookt",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G029": {
    "kcal_per_100g": 31.0,
    "kcal_per_100ml": None,
    "label": "Venkel",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G030": {
    "kcal_per_100g": 15.0,
    "kcal_per_100ml": None,
    "label": "Sla gemengd",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G031": {
    "kcal_per_100g": 22.0,
    "kcal_per_100ml": None,
    "label": "Champignons",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G032": {
    "kcal_per_100g": 22.0,
    "kcal_per_100ml": None,
    "label": "Kastanjechampignons",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G033": {
    "kcal_per_100g": 34.0,
    "kcal_per_100ml": None,
    "label": "Shiitake",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G034": {
    "kcal_per_100g": 33.0,
    "kcal_per_100ml": None,
    "label": "Oesterzwam",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G035": {
    "kcal_per_100g": 81.0,
    "kcal_per_100ml": None,
    "label": "Doperwten",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G036": {
    "kcal_per_100g": 86.0,
    "kcal_per_100ml": None,
    "label": "Mais",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G037": {
    "kcal_per_100g": 47.0,
    "kcal_per_100ml": None,
    "label": "Artisjok",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G038": {
    "kcal_per_100g": 20.0,
    "kcal_per_100ml": None,
    "label": "Asperges wit",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G039": {
    "kcal_per_100g": 20.0,
    "kcal_per_100ml": None,
    "label": "Asperges groen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G040": {
    "kcal_per_100g": 26.0,
    "kcal_per_100ml": None,
    "label": "Pompoen",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G041": {
    "kcal_per_100g": 86.0,
    "kcal_per_100ml": None,
    "label": "Bataat",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G042": {
    "kcal_per_100g": 75.0,
    "kcal_per_100ml": None,
    "label": "Pastinaak",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G043": {
    "kcal_per_100g": 42.0,
    "kcal_per_100ml": None,
    "label": "Knolselderij",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G044": {
    "kcal_per_100g": 43.0,
    "kcal_per_100ml": None,
    "label": "Spruitjes",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G045": {
    "kcal_per_100g": 13.0,
    "kcal_per_100ml": None,
    "label": "Paksoi",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G046": {
    "kcal_per_100g": 16.0,
    "kcal_per_100ml": None,
    "label": "Chinese kool",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G047": {
    "kcal_per_100g": 11.0,
    "kcal_per_100ml": None,
    "label": "Waterkers",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G048": {
    "kcal_per_100g": 21.0,
    "kcal_per_100ml": None,
    "label": "Rabarber",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G049": {
    "kcal_per_100g": 30.0,
    "kcal_per_100ml": None,
    "label": "Zeekraal",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "G050": {
    "kcal_per_100g": 30.0,
    "kcal_per_100ml": None,
    "label": "Taugé",
    "std_portion_cl": None,
    "std_portion_g": 150.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA001": {
    "kcal_per_100g": 247.0,
    "kcal_per_100ml": None,
    "label": "Volkoren brood",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA002": {
    "kcal_per_100g": 265.0,
    "kcal_per_100ml": None,
    "label": "Wit brood",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA003": {
    "kcal_per_100g": 240.0,
    "kcal_per_100ml": None,
    "label": "Zuurdesembrood",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA004": {
    "kcal_per_100g": 300.0,
    "kcal_per_100ml": None,
    "label": "Wrap tarwe",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA005": {
    "kcal_per_100g": 290.0,
    "kcal_per_100ml": None,
    "label": "Wrap volkoren",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA006": {
    "kcal_per_100g": 360.0,
    "kcal_per_100ml": None,
    "label": "Rijst ongekookt",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA007": {
    "kcal_per_100g": 130.0,
    "kcal_per_100ml": None,
    "label": "Rijst gekookt",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA008": {
    "kcal_per_100g": 350.0,
    "kcal_per_100ml": None,
    "label": "Pasta ongekookt",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA009": {
    "kcal_per_100g": 150.0,
    "kcal_per_100ml": None,
    "label": "Pasta gekookt",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA010": {
    "kcal_per_100g": 370.0,
    "kcal_per_100ml": None,
    "label": "Havermout",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA011": {
    "kcal_per_100g": 58.0,
    "kcal_per_100ml": None,
    "label": "Aardappel rauw (met schil)",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA012": {
    "kcal_per_100g": 87.0,
    "kcal_per_100ml": None,
    "label": "Aardappel gekookt",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA013": {
    "kcal_per_100g": 124.0,
    "kcal_per_100ml": None,
    "label": "Aardappel gebakken (oven)",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA014": {
    "kcal_per_100g": 87.0,
    "kcal_per_100ml": None,
    "label": "Krieltjes gekookt",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA015": {
    "kcal_per_100g": 90.0,
    "kcal_per_100ml": None,
    "label": "Zoete aardappel gebakken",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA016": {
    "kcal_per_100g": 90.0,
    "kcal_per_100ml": None,
    "label": "Zoete aardappel gekookt",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA017": {
    "kcal_per_100g": 120.0,
    "kcal_per_100ml": None,
    "label": "Quinoa gekookt",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA018": {
    "kcal_per_100g": 83.0,
    "kcal_per_100ml": None,
    "label": "Bulgur gekookt",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "GRA019": {
    "kcal_per_100g": 112.0,
    "kcal_per_100ml": None,
    "label": "Couscous gekookt",
    "std_portion_cl": None,
    "std_portion_g": 35.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K001": {
    "kcal_per_100g": 356.0,
    "kcal_per_100ml": None,
    "label": "Goudse kaas 48+",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K002": {
    "kcal_per_100g": 274.0,
    "kcal_per_100ml": None,
    "label": "Goudse kaas 30+",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K003": {
    "kcal_per_100g": 380.0,
    "kcal_per_100ml": None,
    "label": "Belegen kaas",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K004": {
    "kcal_per_100g": 400.0,
    "kcal_per_100ml": None,
    "label": "Oude kaas",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K005": {
    "kcal_per_100g": 360.0,
    "kcal_per_100ml": None,
    "label": "Jong belegen",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K006": {
    "kcal_per_100g": 280.0,
    "kcal_per_100ml": None,
    "label": "Mozzarella",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K007": {
    "kcal_per_100g": 200.0,
    "kcal_per_100ml": None,
    "label": "Mozzarella light",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K008": {
    "kcal_per_100g": 264.0,
    "kcal_per_100ml": None,
    "label": "Feta",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K009": {
    "kcal_per_100g": 431.0,
    "kcal_per_100ml": None,
    "label": "Parmezaan",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K010": {
    "kcal_per_100g": 330.0,
    "kcal_per_100ml": None,
    "label": "Geitenkaas zacht",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K011": {
    "kcal_per_100g": 260.0,
    "kcal_per_100ml": None,
    "label": "Geitenkaas 30+",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K012": {
    "kcal_per_100g": 340.0,
    "kcal_per_100ml": None,
    "label": "Roomkaas",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K013": {
    "kcal_per_100g": 160.0,
    "kcal_per_100ml": None,
    "label": "Roomkaas light",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K014": {
    "kcal_per_100g": 280.0,
    "kcal_per_100ml": None,
    "label": "Smeerkaas",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K015": {
    "kcal_per_100g": 160.0,
    "kcal_per_100ml": None,
    "label": "Smeerkaas light",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K016": {
    "kcal_per_100g": 403.0,
    "kcal_per_100ml": None,
    "label": "Cheddar",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K017": {
    "kcal_per_100g": 353.0,
    "kcal_per_100ml": None,
    "label": "Blauwe kaas",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K018": {
    "kcal_per_100g": 174.0,
    "kcal_per_100ml": None,
    "label": "Ricotta",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K019": {
    "kcal_per_100g": 430.0,
    "kcal_per_100ml": None,
    "label": "Mascarpone",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "K020": {
    "kcal_per_100g": 98.0,
    "kcal_per_100ml": None,
    "label": "Hüttenkäse vol",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "N001": {
    "kcal_per_100g": 579.0,
    "kcal_per_100ml": None,
    "label": "Amandelen",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "N002": {
    "kcal_per_100g": 654.0,
    "kcal_per_100ml": None,
    "label": "Walnoten",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "N003": {
    "kcal_per_100g": 553.0,
    "kcal_per_100ml": None,
    "label": "Cashewnoten",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "N004": {
    "kcal_per_100g": 567.0,
    "kcal_per_100ml": None,
    "label": "Pinda's",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "N005": {
    "kcal_per_100g": 628.0,
    "kcal_per_100ml": None,
    "label": "Hazelnoten",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O001": {
    "kcal_per_100g": 884.0,
    "kcal_per_100ml": None,
    "label": "Olijfolie",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O002": {
    "kcal_per_100g": 884.0,
    "kcal_per_100ml": None,
    "label": "Zonnebloemolie",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O003": {
    "kcal_per_100g": 892.0,
    "kcal_per_100ml": None,
    "label": "Kokosolie",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O004": {
    "kcal_per_100g": 717.0,
    "kcal_per_100ml": None,
    "label": "Roomboter",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O005": {
    "kcal_per_100g": 360.0,
    "kcal_per_100ml": None,
    "label": "Halvarine",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O006": {
    "kcal_per_100g": 720.0,
    "kcal_per_100ml": None,
    "label": "Margarine",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O007": {
    "kcal_per_100g": 720.0,
    "kcal_per_100ml": None,
    "label": "Bak & braad vloeibaar",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O008": {
    "kcal_per_100g": 884.0,
    "kcal_per_100ml": None,
    "label": "Sesamolie",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O009": {
    "kcal_per_100g": 884.0,
    "kcal_per_100ml": None,
    "label": "Walnootolie",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O010": {
    "kcal_per_100g": 884.0,
    "kcal_per_100ml": None,
    "label": "Avocado-olie",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O011": {
    "kcal_per_100g": 680.0,
    "kcal_per_100ml": None,
    "label": "Mayonaise",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O012": {
    "kcal_per_100g": 300.0,
    "kcal_per_100ml": None,
    "label": "Mayonaise light",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O013": {
    "kcal_per_100g": 480.0,
    "kcal_per_100ml": None,
    "label": "Pesto groen",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O014": {
    "kcal_per_100g": 650.0,
    "kcal_per_100ml": None,
    "label": "Aioli",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O015": {
    "kcal_per_100g": 340.0,
    "kcal_per_100ml": None,
    "label": "Room 35%",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O016": {
    "kcal_per_100g": 300.0,
    "kcal_per_100ml": None,
    "label": "Crème fraîche",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O017": {
    "kcal_per_100g": 720.0,
    "kcal_per_100ml": None,
    "label": "Smeerbaar boterproduct",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O018": {
    "kcal_per_100g": 900.0,
    "kcal_per_100ml": None,
    "label": "Spekvet",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O019": {
    "kcal_per_100g": 900.0,
    "kcal_per_100ml": None,
    "label": "Eendenvet",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "O020": {
    "kcal_per_100g": 900.0,
    "kcal_per_100ml": None,
    "label": "Ghee",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P001": {
    "kcal_per_100g": 110.0,
    "kcal_per_100ml": None,
    "label": "Kipfilet rauw",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P002": {
    "kcal_per_100g": 114.0,
    "kcal_per_100ml": None,
    "label": "Kalkoenfilet rauw",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P003": {
    "kcal_per_100g": 120.0,
    "kcal_per_100ml": None,
    "label": "Runderbiefstuk mager",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P004": {
    "kcal_per_100g": 137.0,
    "kcal_per_100ml": None,
    "label": "Rundergehakt mager 5%",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P005": {
    "kcal_per_100g": 120.0,
    "kcal_per_100ml": None,
    "label": "Varkenshaas",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P006": {
    "kcal_per_100g": 208.0,
    "kcal_per_100ml": None,
    "label": "Zalm vers",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P007": {
    "kcal_per_100g": 82.0,
    "kcal_per_100ml": None,
    "label": "Kabeljauw",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P008": {
    "kcal_per_100g": 132.0,
    "kcal_per_100ml": None,
    "label": "Tonijn vers",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P009": {
    "kcal_per_100g": 85.0,
    "kcal_per_100ml": None,
    "label": "Garnalen",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P010": {
    "kcal_per_100g": 205.0,
    "kcal_per_100ml": None,
    "label": "Makreel",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P011": {
    "kcal_per_100g": 155.0,
    "kcal_per_100ml": None,
    "label": "Ei heel",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P012": {
    "kcal_per_100g": 52.0,
    "kcal_per_100ml": None,
    "label": "Eiwit los",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P013": {
    "kcal_per_100g": 60.0,
    "kcal_per_100ml": None,
    "label": "Magere kwark",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P014": {
    "kcal_per_100g": 62.0,
    "kcal_per_100ml": None,
    "label": "Skyr naturel",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P015": {
    "kcal_per_100g": 55.0,
    "kcal_per_100ml": None,
    "label": "Magere yoghurt",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P016": {
    "kcal_per_100g": 72.0,
    "kcal_per_100ml": None,
    "label": "Hüttenkäse light",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P017": {
    "kcal_per_100g": 116.0,
    "kcal_per_100ml": None,
    "label": "Linzen gekookt",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P018": {
    "kcal_per_100g": 164.0,
    "kcal_per_100ml": None,
    "label": "Kikkererwten gekookt",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P019": {
    "kcal_per_100g": 132.0,
    "kcal_per_100ml": None,
    "label": "Zwarte bonen",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P020": {
    "kcal_per_100g": 127.0,
    "kcal_per_100ml": None,
    "label": "Kidneybonen",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P021": {
    "kcal_per_100g": 139.0,
    "kcal_per_100ml": None,
    "label": "Witte bonen",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P022": {
    "kcal_per_100g": 81.0,
    "kcal_per_100ml": None,
    "label": "Doperwten (eiwitbron)",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P023": {
    "kcal_per_100g": 76.0,
    "kcal_per_100ml": None,
    "label": "Tofu naturel",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P024": {
    "kcal_per_100g": 193.0,
    "kcal_per_100ml": None,
    "label": "Tempeh",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P025": {
    "kcal_per_100g": 121.0,
    "kcal_per_100ml": None,
    "label": "Edamame",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P026": {
    "kcal_per_100g": 105.0,
    "kcal_per_100ml": None,
    "label": "Kipfilet beleg naturel",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P027": {
    "kcal_per_100g": 117.0,
    "kcal_per_100ml": None,
    "label": "Rosbief naturel",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P028": {
    "kcal_per_100g": 90.0,
    "kcal_per_100ml": None,
    "label": "Heek",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P029": {
    "kcal_per_100g": 96.0,
    "kcal_per_100ml": None,
    "label": "Tilapia",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P030": {
    "kcal_per_100g": 150.0,
    "kcal_per_100ml": None,
    "label": "Sardines in water",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P031": {
    "kcal_per_100g": 120.0,
    "kcal_per_100ml": None,
    "label": "Seitan",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P032": {
    "kcal_per_100g": 90.0,
    "kcal_per_100ml": None,
    "label": "Quorn stukjes",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P033": {
    "kcal_per_100g": 110.0,
    "kcal_per_100ml": None,
    "label": "Tartaar mager",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P034": {
    "kcal_per_100g": 165.0,
    "kcal_per_100ml": None,
    "label": "Kipdij zonder vel",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P035": {
    "kcal_per_100g": 59.0,
    "kcal_per_100ml": None,
    "label": "Griekse yoghurt 0%",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P036": {
    "kcal_per_100g": 124.0,
    "kcal_per_100ml": None,
    "label": "Bruine bonen",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P037": {
    "kcal_per_100g": 86.0,
    "kcal_per_100ml": None,
    "label": "Mosselen",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P038": {
    "kcal_per_100g": 173.0,
    "kcal_per_100ml": None,
    "label": "Sojabonen",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P039": {
    "kcal_per_100g": 155.0,
    "kcal_per_100ml": None,
    "label": "Ei gekookt",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "P040": {
    "kcal_per_100g": 130.0,
    "kcal_per_100ml": None,
    "label": "Kipgehakt mager",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "S001": {
    "kcal_per_100g": 100.0,
    "kcal_per_100ml": None,
    "label": "Ketchup",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "S002": {
    "kcal_per_100g": 66.0,
    "kcal_per_100ml": None,
    "label": "Mosterd",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "S003": {
    "kcal_per_100g": 200.0,
    "kcal_per_100ml": None,
    "label": "BBQ saus",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "S004": {
    "kcal_per_100g": 250.0,
    "kcal_per_100ml": None,
    "label": "Sweet chilisaus",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "S005": {
    "kcal_per_100g": 53.0,
    "kcal_per_100ml": None,
    "label": "Sojasaus",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "S006": {
    "kcal_per_100g": 24.0,
    "kcal_per_100ml": None,
    "label": "Passata",
    "std_portion_cl": None,
    "std_portion_g": 50.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "S007": {
    "kcal_per_100g": 39.0,
    "kcal_per_100ml": None,
    "label": "Tomatenblokjes (blik)",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "S008": {
    "kcal_per_100g": None,
    "kcal_per_100ml": None,
    "label": "Tomatenpuree",
    "std_portion_cl": None,
    "std_portion_g": 15.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "S009": {
    "kcal_per_100g": None,
    "kcal_per_100ml": 1.0,
    "label": "Groentebouillon (bereid)",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": 250.0,
    "unit": "ml",
    "zero_blauw": False,
    "zero_paars": False
  },
  "S010": {
    "kcal_per_100g": None,
    "kcal_per_100ml": None,
    "label": "Knoflookpasta",
    "std_portion_cl": None,
    "std_portion_g": 10.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN001": {
    "kcal_per_100g": 340.0,
    "kcal_per_100ml": None,
    "label": "Winegums",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN002": {
    "kcal_per_100g": 320.0,
    "kcal_per_100ml": None,
    "label": "Drop",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN003": {
    "kcal_per_100g": 350.0,
    "kcal_per_100ml": None,
    "label": "Haribo mix",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN004": {
    "kcal_per_100g": 410.0,
    "kcal_per_100ml": None,
    "label": "Toffees",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN005": {
    "kcal_per_100g": 430.0,
    "kcal_per_100ml": None,
    "label": "Fudge",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN006": {
    "kcal_per_100g": 390.0,
    "kcal_per_100ml": None,
    "label": "Karamelsnoep",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN007": {
    "kcal_per_100g": 535.0,
    "kcal_per_100ml": None,
    "label": "Melkchocolade",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN008": {
    "kcal_per_100g": 600.0,
    "kcal_per_100ml": None,
    "label": "Pure chocolade 70%",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN009": {
    "kcal_per_100g": 540.0,
    "kcal_per_100ml": None,
    "label": "Witte chocolade",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN010": {
    "kcal_per_100g": 490.0,
    "kcal_per_100ml": None,
    "label": "M&M's",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN011": {
    "kcal_per_100g": 480.0,
    "kcal_per_100ml": None,
    "label": "Snickers",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN012": {
    "kcal_per_100g": 450.0,
    "kcal_per_100ml": None,
    "label": "Mars",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN013": {
    "kcal_per_100g": 510.0,
    "kcal_per_100ml": None,
    "label": "KitKat",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN014": {
    "kcal_per_100g": 540.0,
    "kcal_per_100ml": None,
    "label": "Tony's Chocolonely reep",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN015": {
    "kcal_per_100g": 470.0,
    "kcal_per_100ml": None,
    "label": "Oreo",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN016": {
    "kcal_per_100g": 480.0,
    "kcal_per_100ml": None,
    "label": "Speculaas",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN017": {
    "kcal_per_100g": 430.0,
    "kcal_per_100ml": None,
    "label": "Stroopwafel",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN018": {
    "kcal_per_100g": 390.0,
    "kcal_per_100ml": None,
    "label": "Cake plak",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN019": {
    "kcal_per_100g": 420.0,
    "kcal_per_100ml": None,
    "label": "Muffin",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN020": {
    "kcal_per_100g": 460.0,
    "kcal_per_100ml": None,
    "label": "Brownie",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN021": {
    "kcal_per_100g": 535.0,
    "kcal_per_100ml": None,
    "label": "Chips naturel",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN022": {
    "kcal_per_100g": 540.0,
    "kcal_per_100ml": None,
    "label": "Chips paprika",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN023": {
    "kcal_per_100g": 490.0,
    "kcal_per_100ml": None,
    "label": "Tortillachips",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN024": {
    "kcal_per_100g": 520.0,
    "kcal_per_100ml": None,
    "label": "Nacho's met kaas",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN025": {
    "kcal_per_100g": 600.0,
    "kcal_per_100ml": None,
    "label": "Borrelnoten",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN026": {
    "kcal_per_100g": 470.0,
    "kcal_per_100ml": None,
    "label": "Zoutjes",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN027": {
    "kcal_per_100g": 220.0,
    "kcal_per_100ml": None,
    "label": "Roomijs vanille",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN028": {
    "kcal_per_100g": 320.0,
    "kcal_per_100ml": None,
    "label": "Magnum Classic",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN029": {
    "kcal_per_100g": 260.0,
    "kcal_per_100ml": None,
    "label": "Ben & Jerry's",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN030": {
    "kcal_per_100g": 110.0,
    "kcal_per_100ml": None,
    "label": "Waterijs",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN031": {
    "kcal_per_100g": 350.0,
    "kcal_per_100ml": None,
    "label": "Cheesecake",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN032": {
    "kcal_per_100g": 290.0,
    "kcal_per_100ml": None,
    "label": "Tiramisu",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN033": {
    "kcal_per_100g": 400.0,
    "kcal_per_100ml": None,
    "label": "Donut",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN034": {
    "kcal_per_100g": 450.0,
    "kcal_per_100ml": None,
    "label": "Croissant chocolade",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN035": {
    "kcal_per_100g": 550.0,
    "kcal_per_100ml": None,
    "label": "Pindarotsjes",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN036": {
    "kcal_per_100g": 480.0,
    "kcal_per_100ml": None,
    "label": "Chocoladekoekje",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN037": {
    "kcal_per_100g": 420.0,
    "kcal_per_100ml": None,
    "label": "Macaron",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN038": {
    "kcal_per_100g": 410.0,
    "kcal_per_100ml": None,
    "label": "Churros",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN039": {
    "kcal_per_100g": 120.0,
    "kcal_per_100ml": None,
    "label": "Milkshake",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN040": {
    "kcal_per_100g": 200.0,
    "kcal_per_100ml": None,
    "label": "Frappé met slagroom",
    "std_portion_cl": None,
    "std_portion_g": None,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN041": {
    "kcal_per_100g": 480.0,
    "kcal_per_100ml": None,
    "label": "Brownie met noten",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN042": {
    "kcal_per_100g": 390.0,
    "kcal_per_100ml": None,
    "label": "Red velvet cake",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN043": {
    "kcal_per_100g": 270.0,
    "kcal_per_100ml": None,
    "label": "Cookie dough ijs",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN044": {
    "kcal_per_100g": 500.0,
    "kcal_per_100ml": None,
    "label": "Caramel popcorn",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN045": {
    "kcal_per_100g": 420.0,
    "kcal_per_100ml": None,
    "label": "Chocolade croissant",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN046": {
    "kcal_per_100g": 510.0,
    "kcal_per_100ml": None,
    "label": "Wafel met chocola",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN047": {
    "kcal_per_100g": 350.0,
    "kcal_per_100ml": None,
    "label": "Eclair",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN048": {
    "kcal_per_100g": 550.0,
    "kcal_per_100ml": None,
    "label": "Truffels chocolade",
    "std_portion_cl": None,
    "std_portion_g": 30.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN049": {
    "kcal_per_100g": 580.0,
    "kcal_per_100ml": None,
    "label": "Speculoos pasta",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  },
  "SN050": {
    "kcal_per_100g": 540.0,
    "kcal_per_100ml": None,
    "label": "Nutella",
    "std_portion_cl": None,
    "std_portion_g": 100.0,
    "std_portion_ml": None,
    "unit": "gram",
    "zero_blauw": False,
    "zero_paars": False
  }
}
